---
# install-apache.yml - More reliable deployment with proper apt handling
- name: Install Apache on web servers
  hosts: webservers
  become: true
  gather_facts: false
  serial: 1  # Process one server at a time to avoid any issues

  pre_tasks:
    # Only use essential pre-tasks to avoid syntax errors
    - name: Kill any running apt processes
      shell: "pkill -f apt || true"
      changed_when: false
      failed_when: false

    - name: Remove apt lock files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/cache/apt/archives/lock
      failed_when: false

    - name: Reconfigure dpkg
      shell: "dpkg --configure -a || true"
      changed_when: false
      failed_when: false

    - name: Wait for system to settle
      pause:
        seconds: 5

  tasks:
    - name: Update apt cache and install Apache, PHP, and required packages
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
          - php-pgsql
        state: present
        update_cache: true
        cache_valid_time: 86400
        install_recommends: false
        force_apt_get: true
      register: package_install
      retries: 5
      delay: 15
      until: package_install is success
      notify: Restart Apache

    - name: Enable required Apache modules
      command: "a2enmod {{ item }}"
      args:
        creates: "/etc/apache2/mods-enabled/{{ item }}.load"
      loop:
        - headers
        - ssl
        - rewrite
      notify: Restart Apache
      changed_when: false

    - name: Apply security hardening to Apache configuration
      template:
        src: templates/security.conf.j2
        dest: /etc/apache2/conf-available/security.conf
        owner: root
        group: root
        mode: '0644'
        validate: 'apache2ctl -t -f %s'
      notify: Restart Apache

    - name: Enable Apache security configuration
      command: a2enconf security
      args:
        creates: /etc/apache2/conf-enabled/security.conf
      notify: Restart Apache

    - name: Create server information page
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Create PHP info page with access restrictions
      template:
        src: templates/info.php.j2
        dest: /var/www/html/info.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure hosts file for internal name resolution
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        backup: true

    - name: Apply restrictive permissions to Apache configuration
      file:
        path: /etc/apache2
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: true
      notify: Restart Apache

    - name: Ensure Apache service is running and enabled
      service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
