---
- name: Collect SSH host keys
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Scan bastion SSH key for local known_hosts
      command: "ssh-keyscan {{ ansible_host | default(inventory_hostname) }}"
      delegate_to: localhost
      register: "bastion_key"
      changed_when: false

    - name: Ensure local known_hosts exists with proper permissions
      file:
        path: "~/.ssh/known_hosts"
        state: touch
        mode: '0600'
      delegate_to: localhost
      changed_when: false

    - name: Add bastion key to local known_hosts
      blockinfile:
        path: "~/.ssh/known_hosts"
        marker: "# {mark} Bastion host key managed by Ansible"
        block: "{{ bastion_key.stdout }}"
        mode: '0600'
      delegate_to: localhost
      changed_when: true

    - name: Scan web server SSH keys through bastion
      command: "ssh-keyscan {{ hostvars[item]['ansible_host'] }}"
      register: internal_keys
      with_items: "{{ groups['webservers'] }}"
      changed_when: false

    - name: Collect all internal server keys in structured format
      set_fact:
        all_internal_keys: "{% for result in internal_keys.results %}{{ result.stdout }}{% endfor %}"

- name: Update local known_hosts with internal server keys
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add internal server keys to local known_hosts
      blockinfile:
        path: "~/.ssh/known_hosts"
        marker: "# {mark} Internal servers managed by Ansible"
        block: "{{ hostvars[groups['bastion'][0]]['all_internal_keys'] }}"
        mode: '0600'
      changed_when: true
