# infrastructure/ansible/inventory/hosts.yml
---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # Database connection details
    db_host: "private-app-db-cluster-do-user-21984402-0.g.db.ondigitalocean.com"
    db_port: 25060
    db_name: "nodejs_db"
    db_user: "nodejs_user"
    db_ssl: "false"

  children:
    jumpbox:
      hosts:
        bastion:
          ansible_host: 165.227.163.186

    nodejs_servers:
      vars:
        ansible_ssh_common_args: "-o ProxyCommand=\"ssh -W %h:%p -i ~/.ssh/id_rsa root@165.227.163.186\""
      
      hosts:
        nodejs_app1:
          ansible_host: "10.10.1.4"
          public_ip: "167.99.254.135"
          app_name: "user-service"
          app_port: 3000
          app_image: "cyclon/user-service:v1.0.0"
          
        nodejs_app2:
          ansible_host: "10.10.1.6"
          public_ip: "159.89.97.94"
          app_name: "task-service"
          app_port: 3001
          app_image: "cyclon/task-service:v1.0.0"
          env_extras:
            USER_SERVICE_URL: "http://10.10.1.4:3000"