php_version          = "8.2"
nodejs_version       = "18"
region               = "fra1"        # Frankfurt 1
droplet_size         = "s-2vcpu-2gb" # 2 vCPUs, 2GB RAM
ssh_key              = "paysoko_assessment"
do_bucket_name       = "paysoko-assessment"
db_user_service      = "user-service"
db_task_service      = "task-service"
task_service_db_user = "task-svc-usr"
user_service_db_user = "usr-svc-usr"
